"""remodeling

Revision ID: b09a01d3dc67
Revises: 43cdb01d7e20
Create Date: 2016-10-16 00:55:48.036243

"""

# revision identifiers, used by Alembic.
revision = 'b09a01d3dc67'
down_revision = '43cdb01d7e20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type')
    ### end Alembic commands ###
